### ISSUE TITLE
Non-staged payload 

### ISSUE THREAD

**Issue by pple7000** [GuillaumeOrlando/FUD-Engine#1]
Does this tool support 1.windows/meterpreter_reverse_tcp
2.windows/shell_reverse_tcp
?

**Comment by GuillaumeOrlando** [comment]
It only work with windows/meterpreter/reverse_tcp for now. The project is a bit old, so i don't know about the FUD part anymore. Their is a test sample that you can scan: Bin/temp/certmgr.exe (no distribute scanner please). About 1 year ago  it was 98%+ FUD.

Ping me if you want some help !

**Comment by GuillaumeOrlando** [comment]
And i've never translate the tool, if you want me to, i'll be glad to do so.

**Comment by pple7000** [comment]
Thanks for your respond.

**Comment by pple7000** [comment]
The payload may be undetected.However,when metasploit sent the stage to the victim (meterpreter/reverse_tcp),and most antivirus will detect the dropped dll,any idea to bypass that?

**Comment by GuillaumeOrlando** [comment]
Can you PM me on Twitter ? -> https://twitter.com/BoyHomard?s=09

**Comment by pple7000** [comment]
I'm sorry.I don't have twitter.
Maybe another media or just a small talks here, thanks.

**Comment by GuillaumeOrlando** [comment]
No problem. This project is so old that nobody will read this ^^
What do you want to achieve ? Bypass runtime AV scan ?

**Comment by pple7000** [comment]
Yes,encoding the dropped dll is my first question

**Comment by pple7000** [comment]
Just like this https://github.com/phackt/stager.dll

**Comment by pple7000** [comment]
However,https://github.com/phackt/stager.dll is still caught by some top antivirus

**Comment by GuillaumeOrlando** [comment]
Why not trying to kill the AV before doing anything else ?

**Comment by pple7000** [comment]
I have to do another thing.Maybe respond you one day later

**Comment by pple7000** [comment]
Thank you

**Comment by GuillaumeOrlando** [comment]
The fact is that by using public tools, your always going to end up with a semi-fud payload. Write your own payload if you are really looking for something fud

**Comment by GuillaumeOrlando** [comment]
Np, reach me when your available

**Comment by pple7000** [comment]
https://github.com/GuillaumeOrlando/FUD-Engine/issues/1#issuecomment-490296361

I don't have any opportunity to kill it.Because when the victim click the payload(undetected),the metasploit will send the stage(detected),and av will catch it.And meterpreter will die.

What l want is "undetected payload+undetected stage"(in windows/meterpreter/reverse_tcp,and windows/meterpreter_reverse_tcp is a non-staged payload>(better choice) so that av won't catch it.
My thoughts is right?

**Comment by pple7000** [comment]
And using the powershell is a great way

**Comment by pple7000** [comment]
https://github.com/GuillaumeOrlando/FUD-Engine/issues/1#issuecomment-490009896
I think it is a great idea.
